name: CI

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

jobs:
  linux-tests:
    name: Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      OS: 'linux'
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9']
    steps:
      - name: Checkout Pull Requests
        uses: actions/checkout@v2

      - name: Install test dependencies
        shell: bash
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev libegl1-mesa libxkbcommon-x11-0 xterm --fix-missing

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest" 
          python-version: ${{ matrix.PYTHON_VERSION }}
          channel-priority: "strict"
          channels: "conda-forge"  
          mamba-version: "*"
          show-channel-urls: true 

      - name: Install project dependencies
        shell: bash -l {0}
        run: |
          mamba install --file requirements/run.txt -y -q
          mamba install --file requirements/test.txt -y -q
          mamba install Semi-ATE-STDF -y -q
          python -m pip install git+https://github.com/goanpeca/spyder.git@fix/internal-plugs-for-ext-tests
          cd Plugins/TDKMicronas
          python setup.py develop
          cd ../..

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install -e .

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: build Web-UI dependencies
        run: |
          cd ATE/Tester/TES/ui/angular/mini-sct-gui
          npm i -g @angular/cli
          npm install
          ng build
          cd ../../../../../..

      - name: Run manifest checks
        shell: bash -l {0}
        run: check-manifest

#      - name: Run style checks
#        shell: bash -l {0}
#        run: |
#          pre-commit run -a

      - name: Run tests
        shell: bash -l {0}
        run: |
          xvfb-run --auto-servernum pytest tests/ATE/TCC --cov=ATE
          xvfb-run --auto-servernum pytest tests/ATE/spyder --cov=ATE
          xvfb-run --auto-servernum pytest tests/ATE/TES/apps --cov=ATE
